# Generated by Django 4.1.3 on 2022-12-12 23:14

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('AppBlog', '0002_remove_post_exceptr_remove_post_slug_post_subtitle_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='post',
            name='imagen',
            field=models.ImageField(null=True, upload_to=None),
        ),
    ]
